version: '3' 
services:
  flask_alpine:
    image: "auth_service"
    ports:
      - 5000
    volumes:
      - "$PWD:/app"
    networks:
      auth:
        ipv4_address: '200.100.50.5'

  mongodb:
    image: "mongo:latest"
    ports:
      - 27017
    volumes:
      - "db:/data/db"
    networks:
      auth:
        ipv4_address: '200.100.50.50'

volumes:
  db: {}

networks:  
  auth:
    driver: bridge
    ipam:
      config:
        - subnet: "200.100.50.0/24"






